#! /bin/sh

# stop script when an error occurs
set -e

DB_NAME="hanzi"

psql -q -c "CREATE USER ${DB_NAME}user SUPERUSER PASSWORD 'pass123'"
echo "Created Postgres user '${DB_NAME}user'"

psql -q -c "CREATE DATABASE ${DB_NAME} WITH OWNER ${DB_NAME}user"
echo "Created Postgres database '${DB_NAME}'"

DB_URL="postgres://${DB_NAME}user:pass123@localhost:5432/${DB_NAME}"
echo "POSTGRES_URL='${DB_URL}'" > .env.development.local
echo "Created .env.development.local containing POSTGRES_URL"