#! /bin/sh

# stop script when an error occurs
set -e

# import .env so we can access DB URL
. "./.env.development.local"

psql $POSTGRES_URL -q -f "src/database/init.sql"
psql $POSTGRES_URL -q -f "src/database/character_info_inserts.sql"
echo "Populated database tables"