import Navbar from "../components/Navbar"
import ParentWrapper from "../components/ParentWrapper";
import './globals.css'
import { Inter } from "next/font/google";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ParentWrapper>
        <body className={`${inter.className} pb-16 bg-red-200`}>
          {children}
          <Navbar />
        </body>
      </ParentWrapper>
    </html>
  )
}
